### ISSUE TITLE
Scripts/upgrade.sh was not executed correctly

### ISSUE THREAD

**Issue by tomleetaiwan** [Azure-Samples/service-fabric-java-getting-started#45]
The line needs to be modified from

`sfctl application upgrade --app-id VotingApplication --app-version ${version} --parameters "" --mode "Monitored" `

to below line for Service Fabric for Linux

`sfctl application upgrade --app-id VotingApplication --app-version ${version} --parameters "{}" --mode "Monitored" `

otherwise sfctl will show the error message 

**Loading JSON from string input failed. You can also pass the json argument in a .txt file. 
To do so, set argument value to the absolute path of the text file prefixed by "@". 
If you have passed in a file name, please ensure that the JSON is correct. Error: 
No JSON object could be decoded**

**Comment by rapatchi** [comment]
Thanks for report this will fix this them accordingly

**Comment by rapatchi** [comment]
@tomleetaiwan  fixed this in #46
